-- MySQL Script generated by MySQL Workbench
-- lun. 16 avril 2018 16:50:50 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`techno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`techno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first-Name` VARCHAR(50) NOT NULL,
  `last-Name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `techno_id` INT NOT NULL,
  PRIMARY KEY (`id`, `techno_id`),
  INDEX `fk_User_techno_idx` (`techno_id` ASC),
  CONSTRAINT `fk_User_techno`
    FOREIGN KEY (`techno_id`)
    REFERENCES `mydb`.`techno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HelpRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HelpRequest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(300) NOT NULL,
  `topic` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `techno_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `User_techno_id` INT NOT NULL,
  PRIMARY KEY (`id`, `techno_id`),
  INDEX `fk_Request Help_techno1_idx` (`techno_id` ASC),
  INDEX `fk_HelpRequest_User1_idx` (`User_id` ASC, `User_techno_id` ASC),
  CONSTRAINT `fk_Request Help_techno1`
    FOREIGN KEY (`techno_id`)
    REFERENCES `mydb`.`techno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HelpRequest_User1`
    FOREIGN KEY (`User_id` , `User_techno_id`)
    REFERENCES `mydb`.`User` (`id` , `techno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HelpProposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HelpProposal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `description` VARCHAR(300) NOT NULL,
  `status` VARCHAR(45) NULL,
  `User_id` INT NOT NULL,
  `techno_id` INT NOT NULL,
  PRIMARY KEY (`id`, `User_id`, `techno_id`),
  INDEX `fk_help proposal_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_help proposal_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user proposal` (
  `help proposal_id` INT NOT NULL,
  `help proposal_User_id` INT NOT NULL,
  `help proposal_techno_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  `User_techno_id` INT NOT NULL,
  `Request Help_id` INT NOT NULL,
  `Request Help_techno_id` INT NOT NULL,
  PRIMARY KEY (`help proposal_id`, `help proposal_User_id`, `help proposal_techno_id`, `User_id`, `User_techno_id`, `Request Help_id`, `Request Help_techno_id`),
  INDEX `fk_help proposal_has_User_User1_idx` (`User_id` ASC, `User_techno_id` ASC),
  INDEX `fk_help proposal_has_User_help proposal1_idx` (`help proposal_id` ASC, `help proposal_User_id` ASC, `help proposal_techno_id` ASC),
  INDEX `fk_user proposal_Request Help1_idx` (`Request Help_id` ASC, `Request Help_techno_id` ASC),
  CONSTRAINT `fk_help proposal_has_User_help proposal1`
    FOREIGN KEY (`help proposal_id` , `help proposal_User_id` , `help proposal_techno_id`)
    REFERENCES `mydb`.`HelpProposal` (`id` , `User_id` , `techno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help proposal_has_User_User1`
    FOREIGN KEY (`User_id` , `User_techno_id`)
    REFERENCES `mydb`.`User` (`id` , `techno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user proposal_Request Help1`
    FOREIGN KEY (`Request Help_id` , `Request Help_techno_id`)
    REFERENCES `mydb`.`HelpRequest` (`id` , `techno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
